<?php

namespace Plugin\Coupon\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CouponAvailableConditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouponAvailableConditionRepository extends EntityRepository
{
}
